Missing `#include <algorithm>` in Functional.hpp
1. Missing `#include <algorithm>`
```
In file included from C:\Users\Admin\AppData\Local\Temp\.xmake\250616\_A06D4C99BAEB47BF9D52FB3EAF91C354.cpp:2:
In file included from C:\Users\Admin\AppData\Local\.xmake\packages\m\mathter\v2.0.0\4428b8c9c4454261be12cd053ca4a35b\include\Mathter/Vector.hpp:8:
In file included from C:\Users\Admin\AppData\Local\.xmake\packages\m\mathter\v2.0.0\4428b8c9c4454261be12cd053ca4a35b\include\Mathter/Vector/Arithmetic.hpp:8:
C:\Users\Admin\AppData\Local\.xmake\packages\m\mathter\v2.0.0\4428b8c9c4454261be12cd053ca4a35b\include\Mathter/Vector/../Common/Functional.hpp:126:15: error: no member named 'max' in namespace 'std'
                return std::max(lhs, rhs);
                       ~~~~~^
C:\Users\Admin\AppData\Local\.xmake\packages\m\mathter\v2.0.0\4428b8c9c4454261be12cd053ca4a35b\include\Mathter/Vector/../Common/Functional.hpp:155:15: error: no member named 'min' in namespace 'std'; did you mean 'fmin'?
                return std::min(lhs, rhs);
                       ~~~~~^
```