Create temporary variable temp to hold the result of a.zxy & apply unary minus to the temporary variable instead of directly to Vector constructor.
```
In file included from C:\Users\Admin\AppData\Local\.xmake\packages\m\mathter\v2.0.0\4428b8c9c4454261be12cd053ca4a35b\include\Mathter/Vector.hpp:11:
C:\Users\Admin\AppData\Local\.xmake\packages\m\mathter\v2.0.0\4428b8c9c4454261be12cd053ca4a35b\include\Mathter/Vector/../Matrix/../Vector/Math.hpp:379:45: error: invalid argument type 'Vector' to unary expression
                return FMTA(Vector(a.yzx), Vector(b.zxy), -Vector(a.zxy), Vector(b.yzx));
                                                          ^~~~~~~~~~~~~~
1 error generated.
```